name: Release

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build artifact
      run: make image version=${{ github.event.release.tag_name }}
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image
      run: make image-push version=${{ github.event.release.tag_name }}
